image: "python:3.9"

before_script:
  - pip install poetry tox
  - apt update && apt install tesseract-ocr tesseract-ocr-deu libsane-dev

stages:
  - test

lint:
  stage: test
  script:
    - tox -e lint