image: "python:3.9"

before_script:
  - pip install poetry tox
  - apt update && apt install -y tesseract-ocr tesseract-ocr-deu libsane-dev

stages:
  - test
  - build

lint:
  stage: test
  script:
    - tox -e lint

build-deb:
  stage: build
  before_script:
    - apt install -y build-essential debhelper devscripts equivs dh-virtualenv
  script:
    - ./build-deb.sh
    - mkdir build
    - mv ../*.deb build/

  artifacts:
    paths:
      - build/*