name: Reformat

on:
  push:

jobs:
  black:
    name: Run black/isort
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies
        run: pip install tox && sudo apt install python-sane libsane-dev gcc
      - name: Reformat
        run: tox -e reformat
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Reformat code using black"
          commit_options: '--no-verify --signoff'
          file_pattern: "*.py"
